/// Monthly sales activity at Customer × Product × ActivityType × Scenario grain — 2,381 rows. ActivityTypeKey replaces boolean flags — strict star schema. Covers New Logo, Renewal, and Upsell motions.
table '[Fact] Sales Activity'
	lineageTag: 4d76a579-7714-4a54-ae1e-491d1a99d946

	/// Row surrogate key. Hidden.
	column 'Fact Sales Key'
		dataType: string
		isHidden
		lineageTag: 1e824497-0780-49f6-b8b4-a08298a92104
		summarizeBy: none
		sourceColumn: FactSalesKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Customer. Hidden.
	column 'Customer Key'
		dataType: string
		isHidden
		lineageTag: 87d730cb-588c-45d6-a3e5-1c67c31253cf
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Product. Hidden.
	column 'Product Key'
		dataType: string
		isHidden
		lineageTag: e7f65320-8141-4528-b62e-0eedfea51619
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Date. Hidden.
	column 'Date Key'
		dataType: string
		isHidden
		lineageTag: 84c75407-0f93-4cb3-985d-c6d7e3c2332f
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Scenario. Hidden.
	column 'Scenario Key'
		dataType: string
		isHidden
		lineageTag: dd5fac63-6d5a-43f6-9e2e-c76374d24c9c
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Activity Type. Hidden. Replaces IsNewLogo/IsRenewal boolean flags.
	column 'Activity Type Key'
		dataType: string
		isHidden
		lineageTag: 45585dc3-ab92-47c8-bb78-d7522a224a49
		summarizeBy: none
		sourceColumn: ActivityTypeKey

		annotation SummarizationSetBy = Automatic

	/// Monthly recurring revenue generated by this sales activity in USD.
	column Revenue
		dataType: double
		lineageTag: e181cea4-8950-4f4f-9b41-1a3e3623ed1c
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Additional revenue from module or seat expansion at renewal. Zero for New Logo and plain Renewal rows.
	column 'Upsell Revenue'
		dataType: double
		lineageTag: edd23151-dd0a-4d8a-81f1-3ed7dc06364c
		summarizeBy: sum
		sourceColumn: UpsellRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Days from first contact to signed contract. Enterprise: 90-180 days; SMB: 14-45 days.
	column 'Sales Cycle Days'
		dataType: int64
		formatString: 0
		lineageTag: 07996efa-a1c3-4103-9075-ae7cc95dfa1c
		summarizeBy: sum
		sourceColumn: SalesCycleDays

		annotation SummarizationSetBy = Automatic

	/// Probability this opportunity resulted in a win (0.0–1.0). New logo: 20-45%; Renewal: 60-90%.
	column 'Win Rate'
		dataType: double
		lineageTag: bf0965e4-4ad7-42b1-890d-c32099c7ff06
		summarizeBy: sum
		sourceColumn: WinRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Annualised contract value: (Revenue + UpsellRevenue) × 12.
	column 'Deal Value (USD)'
		dataType: double
		lineageTag: 9b6cf77a-fec0-4cd1-9756-5496335bcaa3
		summarizeBy: sum
		sourceColumn: DealValue_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// True from January 2026 onward.
	column 'Is Forecast Period'
		dataType: string
		lineageTag: 9bd82da9-b344-43e0-9be7-3090ccd6e525
		summarizeBy: none
		sourceColumn: IsForecastPeriod

		annotation SummarizationSetBy = Automatic

	column GeoKey
		dataType: string
		lineageTag: 8c1cc42f-bae2-4334-934e-f93fbb945239
		summarizeBy: none
		sourceColumn: GeoKey

		annotation SummarizationSetBy = Automatic

	partition FactSalesActivity = m
		mode: import
		source =
				let
				    Source = Csv.Document( File.Contents( DatasetFolder & "\\FactSalesActivity.csv" ),
				        [ Delimiter = ",", Columns = 13, Encoding = 65001, QuoteStyle = QuoteStyle.None ] ),
				    #"Promoted Headers" = Table.PromoteHeaders( Source, [ PromoteAllScalars = true ] ),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Revenue", type number}, {"UpsellRevenue", type number}, {"SalesCycleDays", Int64.Type}, {"WinRate", Percentage.Type}, {"DealValue_USD", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

