table '[Dim] Geography'
	lineageTag: fa61bf26-6b23-444e-b827-1ea4053fef24

	column GeographyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f53ff0f8-a78b-4680-95c1-8bd6cffa412e
		summarizeBy: none
		sourceColumn: GeographyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 68e334f4-202c-4d71-9b8f-9724837989f5
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 0926bb74-94cf-4b22-b790-83efcef7f3ee
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column CountryCode
		dataType: string
		isHidden
		lineageTag: 12c7ceaf-df13-42a6-9424-4cee1b85cce1
		summarizeBy: none
		sourceColumn: CountryCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition '[Dim] Geography' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\LogeshkumarSivakumar\OneDrive - Lumel Technologies Inc\Lumel\Datasets\Enterprise Dataset\V4\DimGeography.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"GeographyKey", Int64.Type}, {"RegionName", type text}, {"CountryName", type text}, {"CountryCode", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"CountryName", "Country"}, {"RegionName", "Region"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

