/// Product dimension with three-level hierarchy (Category > Sub Category > Product Name) and commercial attributes including cost, price, margin, and shelf life. Joined to [Fact] Sales on Product Key.
table '[Dim] Product'
	lineageTag: 654ad055-da3e-4fe0-831a-d6edb96af7f6

	/// Surrogate primary key. Hidden — used for relationship join only.
	column 'Product Key'
		dataType: string
		isHidden
		lineageTag: d01a6e16-37ce-41b1-a102-ff9ac1ddbbf8
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	/// Level 1 of the product hierarchy. The five FMCG categories: Beverages, Snacks & Confectionery, Dairy & Chilled, Personal Care, Household Care.
	column Category
		dataType: string
		lineageTag: 08b36c61-2275-47c7-993e-24cf7a943881
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = User

	/// Level 2 of the product hierarchy. Groups products within a category — e.g. Chips & Crisps within Snacks, Shampoo & Conditioner within Personal Care.
	column 'Sub Category'
		dataType: string
		lineageTag: 96ca1478-b6fd-4e79-99fd-d200eccf213f
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = User

	/// Level 3 of the product hierarchy — the individual SKU leaf node. Used in TopN, Sort, and Row Grouping demos in Inforiver Matrix.
	column 'Product Name'
		dataType: string
		lineageTag: 90cc8bf0-4503-4196-92f1-4931fc1ed4b3
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = User

	/// Unit pack size or count — e.g. 500ml, 1kg, 20pc. Drives size-based filtering in the product matrix.
	column 'Pack Size'
		dataType: string
		lineageTag: f5c9d23e-7470-44be-98af-af155cbeb8bf
		summarizeBy: none
		sourceColumn: PackSize

		annotation SummarizationSetBy = User

	/// Fictional brand name derived from the product name prefix. Used for brand-level grouping in the matrix.
	column Brand
		dataType: string
		lineageTag: c489f964-282e-4dd9-b52f-a78a06b4d60d
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = User

	/// Manufacturing or procurement cost per unit in USD. The basis for COGS and gross margin calculations.
	column 'Unit Cost USD'
		dataType: double
		lineageTag: 11d37233-6d9b-4085-80c9-ca6fa8d57a33
		summarizeBy: none
		sourceColumn: UnitCostUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Standard shelf price per unit in USD before any promotional discount is applied. Used to compute RSP vs NSP gap analysis.
	column 'Retail Sell Price USD'
		dataType: double
		lineageTag: 64ac97bf-2e81-49e6-81ad-ec45abf8e9be
		summarizeBy: none
		sourceColumn: RetailSellPriceUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Gross margin percentage for this product at list price. Ranges from 22% (Dairy) to 65% (Personal Care). Used in category margin analysis.
	column 'Gross Margin Pct'
		dataType: double
		lineageTag: 6bc45544-6488-4f1a-a103-eebb6e0355a2
		summarizeBy: none
		sourceColumn: GrossMarginPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Product shelf life in days from manufacture date. Ranges from 14 days (fresh milk) to 730 days (household cleaners). Relevant for inventory freshness analysis.
	column 'Shelf Life Days'
		dataType: int64
		formatString: 0
		lineageTag: e55615d2-3d77-43c0-b212-b89a987fcdd7
		summarizeBy: none
		sourceColumn: ShelfLifeDays

		annotation SummarizationSetBy = Automatic

	/// Performance segmentation applied during data generation: Hero (consistently beats plan), Laggard (consistently misses), or Standard. Used to create visual contrast in variance demos.
	column 'Variance Personality'
		dataType: string
		lineageTag: 7c58b00f-51e1-4d3a-a244-67a8c2181d8e
		summarizeBy: none
		sourceColumn: VariancePersonality

		annotation SummarizationSetBy = User

	hierarchy '[H} Product'
		lineageTag: 697df0b6-99ee-49a4-bb94-910f67636a0f

		level Category
			lineageTag: 4c709318-15d4-4b26-863f-496ef37c9bc5
			column: Category

		level 'Sub Category'
			lineageTag: 9b0b3102-a843-4323-b795-5bc8490b37e8
			column: 'Sub Category'

		level 'Product Name'
			lineageTag: 99bd5567-e10e-4b1f-8775-64f0aa605ebd
			column: 'Product Name'

	partition '[Dim] Product' = m
		mode: import
		source =
				let
				    Source = Csv.Document( File.Contents( DatasetFolder & "\\DimProduct.csv" ),
				        [ Delimiter = ",", Columns = null, Encoding = 65001, QuoteStyle = QuoteStyle.None ] ),
				    #"Promoted Headers" = Table.PromoteHeaders( Source, [ PromoteAllScalars = true ] ),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"UnitCostUSD", type number}, {"RetailSellPriceUSD", type number}, {"GrossMarginPct", type number}, {"ShelfLifeDays", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

