table Date
	lineageTag: 8797b131-1666-4885-9939-c7af06a1699e

	measure 'Max date' = MAX('Date'[Date])
		formatString: General Date
		lineageTag: 9b143d99-8f4c-479a-ad24-33c53ef7b78d

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 9d33886a-4c3d-4c21-9418-caf03bd4d6aa
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86b4f2b3-5c55-43e2-9b85-c115f2118c75
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 9e066033-fdab-430b-b206-9de3bace664b
			defaultHierarchy: LocalDateTable_182813d3-0c01-4d6f-a8f3-dc0f083498f5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 29a22320-6d0b-4377-875a-d5bd8f1c6802
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: 7d065e02-4414-446e-af63-b9d14348100b
		summarizeBy: sum
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: aaf42174-5f94-4e35-b415-9cc9248c3ce5
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 13286f26-1ca8-4470-8890-109be9bbbfb4
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 773c7874-480a-4743-952a-a494fa93acf9
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Inforiver Super Filter Webinar\AdventureWorks Sales .xlsx"), null, true),
				    Date_data_Sheet = Source{[Item="Date_data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Date_data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Year", "Week of Month", each Date.WeekOfMonth([Date]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Week of Month", "Custom", each "W " & Text.From([Week of Month])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Custom", "Week"}}),
				    #"Inserted Month Name" = Table.AddColumn(#"Renamed Columns", "Month Name", each Date.MonthName([Date]), type text),
				    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Month Name", {{"Month Name", each Text.Start(_, 3), type text}}),
				    #"Inserted Month" = Table.AddColumn(#"Extracted First Characters", "Month", each Date.Month([Date]), Int64.Type)
				in
				    #"Inserted Month"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

