table Event
	lineageTag: 052b6118-b386-44ab-b69a-ab391259326b

	column 'Event ID'
		dataType: string
		lineageTag: 042c3475-4054-4c95-aeaa-c621d8502837
		summarizeBy: none
		sourceColumn: Event ID

		annotation SummarizationSetBy = Automatic

	column 'Event Name'
		dataType: string
		lineageTag: 33824684-e203-42f3-b5c8-25099067815e
		summarizeBy: none
		sourceColumn: Event Name

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 3e364a60-de86-42eb-aceb-21b71ed0d441
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Participants
		dataType: int64
		formatString: 0
		lineageTag: 3ca395e1-984f-4b3b-8d4b-f80eff795cd5
		summarizeBy: sum
		sourceColumn: Participants

		annotation SummarizationSetBy = Automatic

	column 'Duration (mins)'
		dataType: int64
		formatString: 0
		lineageTag: 2bf9c047-913e-4c9b-88b9-9e12a28d2f48
		summarizeBy: sum
		sourceColumn: Duration (mins)

		annotation SummarizationSetBy = Automatic

	column 'Event Date Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2d62c019-ce67-4b1c-9ffc-a5ca1cf5573c
		summarizeBy: none
		sourceColumn: Event Date Time

		variation Variation
			isDefault
			relationship: f426b895-590f-407f-acdc-e2a1257fc730
			defaultHierarchy: LocalDateTable_ff811321-4013-4869-96ad-a0f2f4e0ef95.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Event Type'
		dataType: string
		lineageTag: 44fd38af-f84f-4807-94e9-f565531d7591
		summarizeBy: none
		sourceColumn: Event Type

		annotation SummarizationSetBy = Automatic

	column 'Event Format'
		dataType: string
		lineageTag: 42aa56d4-e5b0-4530-81d7-9c11d36025ec
		summarizeBy: none
		sourceColumn: Event Format

		annotation SummarizationSetBy = Automatic

	column 'Event Time (AM/PM)'
		dataType: string
		lineageTag: 456107d5-9364-4e1e-b202-ec764836a2fb
		summarizeBy: none
		sourceColumn: Event Time (AM/PM)

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 93bc664d-5a45-449e-9a4f-8663d7ccd1bb
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: eedcfb6f-4aae-4166-a21e-f9547adc5795
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	partition Event = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jVZdb+I6EP0rFs8rNQkkwL6ltLtFt4iooO2Vqn0wiWmsTWyundBlf/2OnQTsxHArVTRf9hzPnHNm3t5Gj57nj76M4j+1IOhbzTJcElbhQqJXLn7JnB/g7YKXZc1odUJPuCjgQRDCz9yDH//OD+4CLwjR/KvnwR+KV/B4S9Kc0RSrj42N9LtXkjEiM3yC6/Ho5xcNIoCbhH8Qge6X6AHLfMexyCTa5PwjxZK0e6IEi19wHerYgY3A900ID7jC6AeVNS7oH1xRzuDhhpSUYXETyli9XSLMMrTCaU4ZQc8EC0bZO9rUZUkr+GDJGD/qXdFTvVPLVUr8mY0oaAElK73n3epZZ5PtiSAsVYdKrsKYwM2KpoJLvq/QluBSonsiK5QInFY0JdLaC71wXqrSKASRDSMyYSSCZzVscIR62tW5jiU8U2RR8DpDG5LWolm/ULTY5gRXQp1notMQ2vFnZnxz7ecyEalqnhguaSrROArRfS2hKtLi6JoV8Ewh8Ibc9D0TweJl9dmDT60iqNhm+tCWHqQZ2zd1Me7Fjl3ZJzuTj9u8Fi2ESQdhZkFYvoMOCfqHnBiH/y/kUOjP1wfCUAy5xCq455lkbIFMzRy0GziL4EIxP+szriteYohtJNBQwzPWarD0ObYdolFDs00jy34tHAh8z3SIODtiQJyhxmj+q/tqaI1Kk+FMx4lNx0/bxDdBGzBhB0Z55uPvlBQXJDHDxQl0aREiMMk4cRFCx9drJZVDRgxDK6fc1GKP4ZQP5KiMoCMl3Jd8qMmZKwkThyec1w8oMYShXPK+pkWmbDE+HCT6oBX4c8ORg9aF6di6ZZwZEXaMGBuZIEdS8IPqP46uscFVLRoMUYfBtkjw7D0X6IngospTrI/+SopCO8UCdiWiY+bchmE3js6ne5VwAVBnariDNlWdUY4WPLOUsRWY6s5xBhBajSJ0NIqriUiu4VAOGafABEl3tFDVp0xL49KwvgvV0FpZ+Hb/DB0GYW3n5IQLiPJLu0VAX4KposK7ggyE0bWpqGtTBhuMNtEvhJpS1HOvi2pbJJz0kKM4WVp1MKhouXTkFOVtKg4AKHf8d8d/o+8wPiFjtTm/DEaGqaXLDohZBNgOuGMZUuJEoNPZdGiQwYaIxhfWR3VFPoaeMLc6ROSYE66PK8PolxESzr4GL1iyqm102k/PKmiHlMiiX+SYEv5HAwMEgbajdiyA6KB7+q47wZbzwj0qWZNCnwfJbXO+AkO54nCMhaxI+s5Gt2bYqWOKdvamPhtXvAXhdyCULa73e2AAunRZu1NabmA1qamDhr2hpUfGIYBw1J+aHqWESlJc9NuCnYSZIwnX59VmZKq7oS3owkfO85vtqR1hRq7JxbLnmSMbtyeXIZypDnPRA6q4EqnGo0XjJqc1SLc4xi6B9srhQKD88TynDFLQc4axqyLT6wmwJWFF//kX", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Event ID" = _t, #"Event Name" = _t, Location = _t, Participants = _t, #"Duration (mins)" = _t, #"Event Date Time" = _t, #"Event Type" = _t, #"Event Format" = _t, #"Event Time (AM/PM)" = _t, #"Day Name" = _t, #"Day of Week" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Event ID", type text}, {"Event Name", type text}, {"Location", type text}, {"Participants", Int64.Type}, {"Duration (mins)", Int64.Type}, {"Event Date Time", type datetime}, {"Event Type", type text}, {"Event Format", type text}, {"Event Time (AM/PM)", type text}, {"Day Name", type text}, {"Day of Week", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

