table Regions
	lineageTag: e12b2cdc-5755-4452-9f17-298be9760c1c

	column Country
		dataType: string
		lineageTag: 64e2d6c4-5d73-45c0-b62b-890f44724580
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Image URL'
		dataType: string
		lineageTag: 642d9f32-df72-42d2-a771-45404a2c6f71
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Image URL

		annotation SummarizationSetBy = Automatic

	partition Regions = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zJtHj4RQm53/ivVtGYmcxpoFOVNkCkZekHPO9etNf9Z4N5uRbbmlVgNNUcW973vOc27T//7v/2CObV+Tvkn+8S//yJM9+ddmSKoCnMfqv6fJVhDYvzQB+3EuSJOqiXm/TNevBb96t4S/XZbhmOj9yS3JVy7+eUQ2OTewFY6plJKpu+bvINNfrtj//n6N/O3mFQv0z5D9XYftISeoIR+hh1zO62zwmRzNUX3ojwQ12+jL9vpAPzF+HhY7/b2l5/oOG8hN9gt2tBSdgD7BgqZJvxd6y5UobnIjweH61dQqhdPrpRd91g9ER/NFUYTchQ/vO6f8YE6erWK/WKMrNlDFEc8Jta04jDArNrQ1nTeeJ5pTZXddvyIEJI/XHRQsziItspyicZwmPbLmIWPHE1oIhtQMcTXHhtPH91SKfAPHWfjAktFoTiYRNF9TGE0TDNH2uSt7lDUNq3vbDE/vOCMksO4sgSPHMxnozGmXeXSuQfhG+L6FYNOXxkee0vqw5CtpA5/Di3ZdlCpvgONeyQxYSFsZuCmDJWetgb4WU6sh1RLcy7En1vtyr9zyUSLYQf08MDirBr5Yzx9x553yhGIIcsVn8gFGVil9BaP8QvCrs5ntZ1iKQzvPmZdV1prqFG1hdIYWum37Yy3tc5M1pmMWPA82LfHdj/gM4yMZvrfeNxPqTJjcWTehY5C1biqFVRL+eOr0ivooYYQxeBFqIor+3AXMF9Fx0i7kX0F09nWf6POTg8BOJp0KnOPRbjdBYlvgap4P0HCsH98vxfiFNLoQBxY8dBRS5BK0s9Wwetih7DulF+9bK4JLcqktSdioZw1MxDpCdXgZk51DQ4pqA5Jb6UGX/asUk8r9HXUrOQCf4AIpw/vMaNMyNmMbsr+cn9JykM+PdYI0J+QTRgHZXuAnsvAmcYxn3AEZGec2h8lZWO4IhVxDDCz9t+LoZSJ4q29eOV/U6cozJUcpdUPXYPsQCV6iGxzPZHKTUJJBgCsnep8Gg/EMa03aMMmx4X++sd6RO7Vxj7EmZHx8S//n42FKNrFN0GIvsK14Z1Fb7HZoBNMGSL+cK4tjZ7SfEVM/1RnD3Y7wbb8FjyjQy2N6uZC+rvsT5gWlRGhdqD3dukoHwL2Fb9SE1TbHEm3vnm/FuBD9qWC3ZRPeda2cSn9CCVOZphtXqdGnmKXSDD2Tqy/J8NsDpM4DU01zlEAhmQeZexS1Sxx9KpYvhmCYu+39870huCrfA4wESfL4/bZlO/3yrTfNYtMobr7W5Vg/oGT3A6d+Tc+36pR5dO6UeQsR6o0cKYfHHuvOsbb3mjBEoFRDGWdLfSrEteTTbocJFmXqkvNxrBklfAqUZrrzZ2wPZG3wJzM10EIIiSkY3U74xvTswZvLVYZNuDh72z99+ffzrx5Axur8GMRy8PQpTxRdP1M2fADmUkIRtmTu4zI7FIdixg1MwwLgwpdnokg4GHRQmCFfdiINCVUf29wzbp/Yo43hnioT5amZtohDDrxhrd/T5N4s+aHEod/27hQo8Z2vAVVRbxiLKzhy6Oss7Aqkn9U4sI9XXAa5cxVTr02MMPkpncpt6dS+1j+z85RV3jAQdmCOYScZCKp3sLuvCDtJdhCtjLX+OAZT/Ot/0E7qVO+CKp2KTxtTFOXP4dcgPya3eiJmF4UA7h92o7mVQgq9Q3FI4c2RRoU8X/i0PX9Nna0hKeYppEY3mNQBSq4Lb2LmZQn1WAqRxJb2246orn3OXF0NThqyk+om8Cy04bfYny1ZaCihh8JBtE2HY7CbCtUAE0aEvLQoGNcResHJ7U+k9t2m2fVsrVuQEnvgqzxXHDMIlS1kCctqnYv1mZJWbhc8sy4KGBP1liNbhI3tCH+/A/owffsDpH22pq9sfhWh1A/4a4BtLBM7+c3VwrMWaV2Prz1voPZgs+Lf9PC+rq4RPLcBu7g3imGC6kPkCEptHzXCUlbWFrZ35vysDC1tb1JDz3v7Iqonv3IvuUzrdFwj8AWmJy1XFZvAuSlYrmKHwGS2Lq/6M2rRI9TPk9TOZeao/8i/ZlhgE+N0L+r1kQZGRaUrQTCjkZCPskZipRGrTTmnnrZ9pjFQs1IuJuC6mVIxaMk2PaF7kBP4k+OYzlXMmrk+zvg1Aoz+NJeuCJ+0gw9p9z+WbsHEhxAn7ymPjfEYcWMW1oioDRhhayRarvs+DEZPSXDS2BZfD8l3CwtaFrxoDXF9WXgM85ZBTx9muwtL8OnUc0zlm7BiOa755iIGtGoCthZmr+uwN3bxO6XsYmzz64nbicrRj6/bWUDw09fF7bVvxb0AuYH0ADPoNXV8vbk7IzYHmoNSZ2MUSUZS6afxlIFaMIqIKnVsX3wVHCySr73BCTQ+aKqZYEvkx34Ph5H9wNSPUXlkRskf3GAJl6DJUvPE8bWcXs3kqOUZ6zH4PpdVjYPPoxj0FviGiEyucwfIn7aL50nhAgNIayDktVO+brm2KLfS7YmX5a4VTBz4ZMifrsTgMGE4dBVMaoPZZU0bYy779blnBr3ygaNeuOGUkpzkvegsBfjgZcGIy/c7tcYd3KSMulqwm5m0BpCBlt5UcVqr/j6PK3wedCT3Sor0bYKzGy9GMDILQCNTBC1P3ShG1SpbAIe1NGI8Kb0ZxlD2L8gzpGXWC3AgMYxBGZfO1cch4g5DEwJGfnt6i7f8OWXqy0YApIZPzrksNnHeC3/C1FdPVpxakP4YK0Q+bJI6h9acwWuHdZd6jc7T2ffdafzA3W7ym5hv5dH+5UkxNJRHu5bxwLxF/MXj+hz0TdAfjG6cCeWfxwszztNv+oEVJ1gAniQ0A1HsH9tGF3LfmnF6viEL21WMVWQ0cWy6NhUoG7uDNRreNV5/g2h7sJIEgR+j5J9H+tqcW9cjklK5tiq/7UJ/PaA5Bdjn3iHHpKQMFpp0zs5FbCOs4ktdl31WNIb0dTaxZ6ZfxlDKG5NmsHEtIsWcPYTy6wGc7OtywWsk3tl2GDxCjvwp9d60TqoSBn/JqGPIcT//WYclRR+pCOmK3KYsMMMkdnNYdJQakQDZ6xtwtZvGNgX0W+VcZR5SHfJ5f5pT8rkBYL+Afv6oBPHbfcP/eZaIM6u7gvZxRpS8RET7lWj5N5mFKojJbg9BNQ2wAUI2CFotbtmVmVc3K66AX60AMDBPDx2osAeGfbcyIWIdMkib2SoM/mGfkRwxTYLLYecNK2cwPweo04EEpsFbh4Y2RcSjGbJmfgtvIx06UGIz4HNXRIqcXb7IbFdGJPhrTMO1OEMqCNhGzldMRejMf1NIPa+PrZcc/PhrmxnRBc6BCWTukpTnyhH3aAJVUgSHdrm2yyn7w7pLQucg2zk9bQy4xuge5Ufv/do/oQKD0xLcgoF3qlQYu/lRVoRIzj53iZMB6dTt2Czzh+huY0N9O9kPzJExDJtlisUKcmWKuHl2ws2vxqJQjEG1F6lWQKwTVIm5WqoyaYf5NR8mA3RvpkmuT9mqEHyBu4dG/9loM2EW8DrVMT4Va0LxnrQ/7gh8q480qNMWSZwSRglYh12EAMo2D9GZk5pYq1b3OHYQmR6ZNW2HUmlsounwXQB+slliVilkGDUqqWZFVBKHx72wtW0DZTwmbXxPisLWqtwtXI/tZMlMMglo1rNfOQTTd5WYUVnZ0ummm5b7Hpew8kMel8vZooivTkghtp7AzC1dvnKFD4ewaGSkyV5L3Oo/sxHg6p5HxpfDSv7OmnzF2CH62Uox1Jys0GDe0tUkIzZg3G1Zqsun0ZmUDmQ2mqT+F9YowyjCX8aJOMJ+Gb6oo+OKOFjiGVgCjvZKW9kRrqq57aIcKXlIHzBBaiItLh78AGiHkC+OaXEp+ZqRAC7pZJV6ZfQ3STYJQUwqbGyFydJScgPdK/CLah2XreLmieeSyo6am65CHhcPcmyDUDOB4VSp5GrXlU6wYihFNs5N8YUkNQZCoPJnAWW47Tbsizwm+U/Nxp0lEae0MG7aJM+It1XI6iYj7DOTJSj9wmPpmk+c6QkmmMwaZG09mvU1IF8Vx1iNawhytCkFxtD+UwCzhKAsHieV+pmDeWG9SpsWz6pk/LSw+EX2H792XwwLguZF4ePEzLgjUPvUo9KIr6hVsuhLJBZ/fQUDPOE2S6iHh9tTQe2Lp5ieunjmNbmxstJmkYFyCxZH+wA+X1uJmbHOJ1o0umhKTMlTbPQmgVBF5IBpWU/FRpNZV/nBbGbYgejC2NJ/243dgJLug34AUk0CPkexpbnvXD/K1V4QQ958ItJRykSYQotZXQC7wFodud69w7UXQGOc177hgIXiyVTDclgMiZTUoq4XHWdi75HynjNq06C+cLGY6Z6eJQe5G5JbN/JEzLMHFhN/f63cMe0+1G4xOo+JEUL2kVm9p/yYA6WW3qUDvG8htmytUYU+BccPGp+t8dA57HaBLLhczHIZU16RuJw6PLFGMj7xRgRkfR2OoAc3LH8H8at3Iyq3LQCdxHNq33kfStKbkCULl1X1mjN7WCGKYvcKrQRnvGmgfhgeMCIoIwFlFjPE5a8k0OdS5qM5bdOKLOy5DUbdRR4twIMnLNZfBmOCYj1wcCOZQUlYBm+QYbDhc7QDmQ9qygkNKHpC9w1FSu+TWthSWkliR3BqvydsdsnbSWe7Q9I2KUx2Cd/UJ9hBBACE+xlc1pE0t04iLQrm4JlRBYGpXY5UpEiQrRbdmsK+Q+TqTGxhC2iYsTE4fFt6GUZ8OfIBm+NiarhNvjjK3uqBOlO9MJe5PbaHFVBl6Penn6nW+h6PlYE9oM/B23kZ5d++tOwQFYhFgbt8lrmnHkysFNFQBXpqk1d/VNqyWNGsge4cOvLmdOzMHS70T1GUuPhmB+d0v2EoW1MrgxEiuo5fuh7dz8zEiIzAat2VXyP76OQJl/d1aK0gfKtSFwqxJ4WBFeuPGqcVTR0HUQy/hnUn7XnYGKCNO2n97lMHq4gVkkL96nLdSnyF7+zsy0fcE18kiedLoOYyEEQWtlr8ajvENTHmi03sTu3tBHhtxSRIwFJKVBaD/pLiLkpQH/VInnHGX5TyJ6UyWozt/OXnF5W32c01b6EJOBhAFzCzId9CN2kj/QPdTNhImshQRgkwKQ9XcZAUDm60PPRKKvUY586gKMiqnhSxWCIWoRrhvCGwfiNdpRTM7y3SXWXlcpubwOIO+q7myiPAPcurpWdzOlyffEkDhcxyMo9HRb1ra+vwlydEYFHkbzKOznUiBm7QTrrvifggYnLAyV9MLGBVvacPvxHy14TDgMxXvUep77rUrb9FldRCJm0U9c9eb+MtukERsfRPKyV6VLDiG0yNwOEWsuTryumIdZUQn2kRDTOQBWdqJx4/oILcelPfAeLh/dVwFNtOlswdENfZd+fY4Mtyd73jWH7CDPeh+U7Z+49xlsFNFMsXkuZjLXIYDwNPg4buFVsgFvZVhR6BObkgnk1MUmgbvka1z84hpi+A/JCZfMfgnorOQnkEm5gqg+seK+LYtKUbN7nJggkH0qv3EKPvjLs+VKyLAhjiyevRdH4zpeXVz9FAEJmvVegLdrJomy9LzIbXw7eZs2+OteGMJ4HlVXEp+ks+zcKGML+565nan06Bz46hm1j/k7aGk51RFvwyIBR1rMcIF29pEqdQ76H2XPRa81vzr4/qJPAY6mLk7pVsX/PbgWwjT7wGrJYt/aiJd8CfF1sr+f1yFHfbcGKIrGcQF4OGit2IiudULNu0cR75XP23Fim8KcIxfxK0xilTKIMy91QMcdSJkzQ9eeWXRmlvEG0ZdEMLuf65wqs6Pi6snVpV1b/92z/+x7/8+z+4ZEzy/3NryNyXVcKv8W7x998+ZQs4z/y6v23p64ih7HgpEkM5Ij6xzaI5mh1JiK8ZYtaZ5B8pqo4DgFHS+x6crqqOIPqF+gsGZN98IItvEDw/2duGji4baW/rQ3eoHevazriIq7+G1zedRQhKXCcdUs81VR6+SAf2232XiVgcltQth9rh3PArBGtkV9PdozFbkexsc/ke2ErbSU/tddpvqWdzY6Hy/hHI7zda1sxFX/YnU2kvgP7glCaJQqVFjU8przSof+yXf38RHATt1r6xfpPolu+yeYQB+/6pezAn8eO9NWO/ku6rQocbmhclDbHXY0Sslnnd4MRng1f/zPKQRCYxYKIjsDWErdna3fX3qkMTB3PqOMEL2M6mOw2eE1dXWODQ4BQ0a4TF12Ys/kgSOUvruXuZlJ5APlBVaHAaJ0tSw19B6X9t8aGl+PcOJAyuCmEkcv0lIQhWOjUoJgIky+uKjP7BI8z03grYBu+XrNaMNwGg3xzwJw3WuiXhPAnCbVp76++CUUhMtQWA+uvsTFI33fz5QNqtN4RtDmA6zEV+Y0v8Bo8/+8RnxyBdlpalEFo0Lg79WzTNLdGFNsjJsGKBZTV+twDbriQ612CRieARchKqZ8svHCAps4XiScT7gPxmSQMTRpq2XV94v7Tedh/4A31+ikDH5jnT5WjNoibMjF9VVs91QcKcy1BaulmhoE6AH/Bv5geydMOjx8Z6KGExjIZUL9BXKtfnpQbd4GjhRceKzWEYsRGHo3GXLs/vUpGRLVN6n8WSuJg+4h8sv276Q51ebqPrxQiG8BUNm8Hr5tDvggQlH/gozX4KFP9ayrVWeikEdllxnum7X3qraQe4pttmzNqjqVXDXy7cruna0tTloheq1FdVHa67IEiRkUtgI3OoGbul5+U8zOreEDhkQlenOY2x+DdeccibO0v5hYBy5sw9nmyhYrRAQDFie8SikrejvxEDzGxDLDzYHiZSWoHwBXuB2JtISgQWk/JW+sWdB1PUwRj+UhV2AnkCooZrJ4HQnYA8e+9sh1t38qZsRYfhj4ztKFDzpDEHCmEzLzvrWnkM+k1s0z2mEewITRdV5LJIcbkjnEKHav3DZivyInOM3+vCCpr23KolaKtqfMX7zBuwB25lCmmcsYspzDdcblLn2YoX4dmhfFMiQ4QmFDwSUqShnjZl+tisjX0/+H7EhGVmOCPxlThfM2FLaFwhkQIGM5udKlMW15bvgLYKJVOBUqVRqVQhzCaLHrFGgWhzqYmUjkhoOWPw9Eo8G6NwAI1vmw2Q85C/skI4BSOT3r2PRzFOTJjHIlI9CGusOvVr9GeN2sux7zhqBzMbv2tnZeFF9xnPF/tic7/XP9kqq8kFkcsPTLir9GWUU9tFiIF+KcZ+46Cix13g45NdadzAHFO6xfuApIbTJYQ/008HsOFKYqCgpcquoQSRZHYC7Mw0NQpywccvXBUQxKxex4BHhunp1XN6t45d93/1a20RezA0t82p2XFEXt/3KxuGRlvn90TLWi5Imz+z6q3ep9ayKaN4muyZsxsVMw3tFCbFi7GJr91CbUci0T3uDhQKuSC1kxwmqNgUxTLPFqLdl3l/f2g3/HJPoiuMP3VzuHkU9q274D3xW11S0BD2vQ6gL/piqMGMqS9V+/3tUqUHKASakfuEw4KKzCIv7jMsX6bVsIvtdGT5slJMcobahj9bC72Vg7fyZbVkT1cFZ8Q+OUt+hYf+PexGjh8mZc76TK5K5HHwoXjIjXVAcSvqaq7PdV+nLDmc6ZsyVJlhoJ0wMWb+Vm/hDZUz2Q5UsnjxBWteermdV7R0rbhtqyxY+MCxT0KvcutzdILm/uI+zSEknDTw4SgYi9GLH6oyTox4Bx4EWkk8p3lf6wITvcdFGGOQq2Ue87dXmEPwaXHUCZVdv42lQPaIIeIQDiV7nAp4EIVqsSyFjhcBoYcRt0yWPZjlAICvH1QrmR4vV9xTPl/4LVxq8Db5h7slkhltqjDFE5Y1xq5LpeRnNoc6UKPXmlKn8408sGV7IKSkm2eQCRQRawnCOuY5l0HCn/LZXUX0vsEwIvui9VLebb9QTwbghcmAO60vEIS8DdPswpYpQFe8+kde8KGLQcBo+XzMiq3sz4WSGG0dCB6CmcJISvnGekChAD4ks7BvipJRi5J/sJMEyTEPz3O9Y49KBJ6XbXUwJz9IJCQDWGAdN7/ycwktrarBVkZMID6AbaE80AQw3lSiGbwqhDaV//x6tTcbHDuBaNoJZmXw2vuctX3uUx3cxWDYvrCLrXf8BaIot8PomwA+1CcG7gyP40+A+Htn22z5ZR7gEGtLirro0dEflALMYGet86Ei+esfIoONXz9KH1WeeVDgFjGppYi3PNb3uUk29Le795K/X9Bp2KwqZdZmZd7xXvLgneOHqFNxM/AHZ+b699l+OmQbwiDHmht/vHin2Pzu5u0mhlH0mRtopvaSQFOAPx/pFwqP8kKVRpHsVYxrAIy/ks8YnGwr5cK3HF0X1n6Mm6WMVRMyqsTb9KNdDN98iovF+PpzwxnmLhcoP+11ccx4F1g4x9Uz068Kg1ehpEeftkh1SH6XzNsJDnBXkK0gNjkGpjvmOzQHEU+A4dinFd90g+N1x524DYP7hxviXA3q0YqoW2VS4DiexlYSkcIty11jPlY5imGyIyKISkS+PT3fncWMcDrg7U9m+DBGE331zDSVUCNcy+5QZtnyHGGS9QUz2nIsiAcNSLAMGTXa9ZO8gABQXGVeutXh7hLsikb1TUjZyQKMjiiNlqFhp88Cm+RdD5L6e7wQOpXgSMHypO83T1klaRWyhB/IgOuUaclffP0V8Rfe9V2Pi/hKpNMrDegIMslqFVj9wjAdnDQArdi3oYjeDei8tKfsM3yp5bh5Ft5T7jH7Hw64jlCYxehAMefv42+GzH2NQn0sANce4L1APvmYg3/RvvZbh2JgR1QVeux56NoC0OnXtBw4IZiM8q4+05z4VLSdbxIsaQ7/eWGWjnjhtxp1aikfsT4BWsptN9wUdKxiOkV4b638AEpUN79rdlLJgul0ylAXFcBLmAk1xGKDm2DmP8kV4pqMWfH/7NkU9C/f5NQrLRXD2/+FZ1OYZPiPZ1PweH/zpRlIRgn+gG5HnY2LGz6NtFMxO9udTuVpFFmgXvDVtvaFVurukoa5mMwRVioC/Zf3YiGyFWi46+zFJ2kSQosyFdOupUbhPL2QlXBXuKr6pidytjeAiHECLwj9Inq6lbXejx46WibonRSN08Q4Ay+YUWZtfcSrYAkhFDgjqxivO6no0EgJI35z2Dse7H2Idcxc3y0Ysw+CEoyJ04M/+URkxoe/SEqQSfIYAVa4LPt3lQyLI6nTxqOD1oS4hifQyxUjN59aPke+rkkFzzBSJZetcZFaKrNjUuayYCyO8MJ9vQZmY40ndiF70pqbU1mNXbaE/R5GaJRGA5zn0vSs+Iai4RQzAovwUOaR5TkaNLWt4wuuc6iA8kbGSsT5kQBuxw53oSqobORKjeArlLzuOFisQVZxgWNWwXH+zg/RTOhMjAl/SqPX/1CfBOsYlcyUGMIJlKnrvX9MFgY8574jBtRCu4zLjHfTqjMm6U9PN9o7scTftAnZieXBIXHb70DaXIgwHSAKrnBaF+foK2/TXtOEHFSvTwD8PH7/zg8luF/EawYH4syV6MPoh31YmqYshECl9/uDmuLc+JqUFeSzbOnPiK7Yf89FOnpQN7blhfThZhywX5irYf62iKNZJjM+3d9Q6TDtIoeijamte0mrV0bNsrbIBES+h2plwDl6LBo0GiOMKXhEfgwF4UP3BvCKcGjTuc838TjT74m1J2B/2s7hQUAa0h7e5+BBNv+lc4G05ZYLGKqbyDafpN/BuuPVERKYHj8jkHaFQWbKKzY1lIRnG12F++Bq7EQJVW3f8zVevg96n7EG82y+lTz8gKT9TIpL6mnQ4g2ci3Fo8XBSwBODewCQ2JN9ss1Wiod6Lw8kVt84pzqC/CBwjUwbcdpABUmzoD4sqyhgDEAc95K7SdNGwPNstS70rEW8GDQG3ritstMWtQUsTkd8p2chM2Q0/e1aAwFuIXO0lK34Kk2kZ5s9Q9tCBlTfasZ41VwMrG5aJen7OmPafmWd3TPlrSRFjCqzQh3J+Fs54xZCrwSpRZEujzGLsWr/sBh04U/1QjZGVqqgMdR297VtVi1H+3582B5rGxExr2w9tAx3h2ppM5FItmSVMesqnSR/uzzDWyR+u5ZjTQbG1rDQ2z976B5xlEQldvjHNi7m9aV1ZFS3w2P3EhheAs8mLCuzfwIVkb/ce3g1Tk8lMh11xOHt5Gwi4gSw40qUtAc2WtayFKkkmJPrmEviv/YgXF4cDgNjdG3F2IU2VZPYJFGD2bB+PiqWN0zJ72OJ9HahTBIPvkDJVBQsRrpcCVLHaTMrMpqO0/36SJwvM30hH7XYRw+ojt10cwenYuyrp2jMtTZZNYw+bc4DoxuHz6+qfx0aUwy2eVsPHZuaF2YknHFbU8cfFuXiFDk8rfrUJW5HBDKCSAwoOz+NwPhtlP2dpzzcQaQS8zHr7KWAquHuYMbFkWGBOLdwKvizBdccpa0mWT1iS39vWFNoHDrAgU80uP0W2a3Nl3aU/a0xiAnHiFIoG67y5BvpXqn2I7OCwU1KLNaCRstYMSLOkEvoFK40K0Jz464PmsPxJH24IvzEhA1JGPqBpQQEQM62EBKlIKe7SkQ0UbEeSqu19lFel8DQxV4DeT8CCCl7dRcWsmuN2JZjZyx2duvpJNk6NyTEhnDIzmY0oi6pTTaYv9DexW6KPZEgd5tO3zrG0+bbB1UH8WezqfsBkPQL26Ir83e4MaF5hLjDbgZfD5/QsLhbXaE67MyC++p4UcZZ9GM+Dk2RnE5HgV1Rsk4CE0aFBXF1YsADIELalnNvspZhEHLvK5ByeuLL6wHrBd/b9JxQfHmoIds+sNhX1c8mUTtJhLr0tHsC0XxK5k4WS2Jgj/WyWqmUHTzRJi3Y0E8JLkRs6FMf90vseRWhZOdyhJvFh9ny1TUkEbZIU3I1k7zn9aBQ/QZjEuKHj1mkSALcVBcVPbQRH71hxEzonWKGSDJnB90X0sC1i4tQZnuDaX6wgUC/MWjcs58tYHC37p6eh+nTxxh5ZKFxHv3ovveCaJPt2dmlaIPdJsvi6y/fUx5psqnnYtZ+UKi0Wc5lFexJMhMExAm3MCTjuFsyhPyg8zh9VDWX+qO8JEHoTRdrriXPgo+5pmL0yguTQtwjeKijMVer2fRPo3r0FV3mu9HeLnW97JYoovRtQYFxih7leaXV6oywHoKo/FaMmjVZKXuIeljS6wiK9VvJ80dRZFSx+4/HqO/QcOlyiECTiHsMkbl6ySoI8oAsl/chQik6/hOdhF70OvewB477J69JxTok4/N/YSFYjv7Xw8My8dXi57+yEMyK5n8sBPcDDE9fwY/qmT7NeQtDXJVEPbAvNxq5og4kcl40GBdXjk1URdWumI6cFLGrClFe+upc4Q5O0dTF8tL3NGpcLZxDCdlSdj5FVT26Ho8WU/U9dYG64UasB/ys+7ANwD38cOynUh1PUl8cKWT6bI3fB8mH9mBACWP2i0sqLq3wDMECXz3w+H4iZsTkX2WOVQAwxSfGnq8wvqE9ekewfXXyeP2beXGSD5dX4g2VhCxjZtJLgBnb96FhY8CI7UHhpOTHZAjqh2DuFin8WPmbIKIN4EziaMAYNzsChmciNpc+j1lVktmExdQGwMLuR51YuVSulCGvvOo4fbG3cticBVM2mxWL5RhlWXLCWjorghWEPdiypXvxNeNs4Xptxkbrje+hmjO0FW0qFFCh2hCp2UrTCPtsaj544/7Ebye27Bvk+Uhf3c/LcGAm/BSPX3scW8TxyikxU1pr6f1SLSZLW2+JrJBBjcNNzVjywlDKJ1AzNxAIVFMMcfxrfxKK8WrpaS43X6qs+LGXVikMGVDuAN1xsiriYNJcGLXVMDGcc0XDaPzIxGSjodrcyM3sj323d4fAvD3zAhnpkVUYXCM+mwI0HAMa825CjgoOY9oxiOtIFBRk97aHqCD2krvfO2vSHRLNQsj8vCgfBN0uNnMzJUQIjs5wNjNTzV0hIzvXoTfATX/nwmxft28ZiHCVAHMdIbzMi3s16B47V9Aa6Q183RcLIN+85jr7bX1HTp3hqgmlcnLDHxi+Hlke/uc1gO4RYOE9N6g5hXA+wxVL+qEfD7zPPD8ZLRLJdlfs4Soxk5DVxuMPhJojZNDW3McxGogGMzTPgm3QBjb9agWyngfdeQK3Mozjj0UzatzWMAlTNuSu9brxBHzwE+TcetVjbJWa6nkU0y/xecC8VT5gRDl2pQy0WmY0Ro/8QaAMdDg0WnwfPKuGNrvJZ2RcbI+4L0P6vi7vz2vyPtLqTWptLzj42Oe8nBkoeVC1QBfjFbR1mw/8IkWhdOqpdY15/nBYvdzuSgoKq4H5B56TyuXdyO/UR1y3i1Sf9tP4AGOi6E9k7QYgvBuQyt83wDF/92K4ErJ1fcmW5Ygkb4ln01BRkK1Uwd0NwK7HQt7pjpinzw3QhAa9RNU6xNZPAx16CauzPpk5YN1CJwAxkR5YqLP21cGKci7fzbzS5+0fEokpHP6MKvGxWxhQ/PljsxGNkBMPRWYEDtrKqJ9p706vKUgRlFqHs3m7CxK5ZzGGbNaR/uGXUJvzCABn2siaW7Hd26M2+ZA2jPHr86CychdsgIrE2/bwc+ReXmkPYfKI1Lo4izYspq6iZDTkrNGIO1pnrRacxWVVc+H7+gg0GpEKBLG/OVvN6OJrK9BB2WKSQk001WW+Xn55Nqzui959aTGx7hKSZMHyasKbD7Tqwc+3cS/1gTI5pP2a4B4tzTygRHHeMbPf4aWY8TW+dGBh1MNxDZi4nYcv1hfkPZQEkUQHe7R7AMz+TxYN/LHZi/y/ac1Y5dPw/6UX8Q3+v70oRHMmEEsE3EnDMFi7nnBFvBlRwF9R9J03osdCiS2KplRieDG8MlxC60nazT3Nm0f4Vuwcwd/sJ5rgauqquJe/EiOyRfXKCfVjfvqPrh7t7w+Dyi8Ef6D9Lc+yoDKKzHKAoHH6liPFYbvFlhhuY/CxLw68QGPJWznnSGYlgOnkhwzjxDGa4x+c4/kvtAeqNz4QhuhtpKHfTbX5hQEuhw2UpyuXxxH0dUQYZOzR4SyVWU+IiOkY82+4zvVqTY82ZzA/VgJrEaKdZkZUjPa4u3c0c69wIceXdmdclx8aQr1PZaguQ6jMr69wfTj+lTSw5aZz8WhYe/Aqy44tem876I9E0lR71pZfb0HTPDBzPSf6+Nv1UHy+QRtBqKXTEKg5xwPVlcSiN/npBBAPxA/8ET2LopfkozgXIfrfp5rWMJZv0T79QPP3b37x0JF8fPjE09gScdtwiqSSU/YF7nCoGhnEFelC7m1d6i22YbnxAvkLCXN2lpZBvMZKampw1uI9SgkAEb1HHgjfef5028bnS1qfdCMOqzT5Zt8niaY88+vvtzVg5UOr7yAuKGu4fysBUghsp3l8FguqhTJzRxKafKc1GCjjfj9VP5gCPPDjKsfdf9TjI6cM76pq13EOHptzyo6kqYdQCyyYxU6oWWoacewSWec58p6j4t3rNlnFqsLwMPElb5/Aw+FeaayEPaaVimQ/F77NufviNvB7NydfgD8Yyo1fFbjH70vrCindMyMLzKhv2IO8RqiMcIUPKrwwgdzgygZ3WIYw5jvvCVslbYEoBJPWRrc4UAkY/WdiDE5iu7ImMj+t6ILHBaVb0i7GCHlLiSiW9xCzgjKrbR9PZdKvz4PD6ZGOQ8ERW5DSCys+qFIcG+LhHSYd++rwCIDovGf7tF365SRKl+JuIav5MqLNyrYMbtGBh+RbG7w9fYeG3mvaN6JrtrjJnlCWMEoTOKGS11dyjfebBHWh/4wXqdDXRgSyj6OLvoLkRLpZE513SkXHJLVG370VXspLwQWTspuuQib3lOEkoOOvh9s9ndaZoifH4Ry5zeOF7KDBz4TzIyxSgr3BxVXz6J2PLtHg2cyRUnt6HutP9+uqAMl1iFUShYkUFcRdoxMSXP0ZtVWBBBv5vFh1F1Ya2VkNwW/oQj8OOMsLzV4W7hP1Fgqo6P5411GlqfHcV+fcN7MyqrBwCITHY9YoCYSOu158e0kUrw2dPit3Ii0Xn6jJcf0XlBiA2UTH6SctvgBC2dryHIqLuXgfRQ+FVuiwwvPU+Yjx099GUw1ifexuaHPOmMaOImHSyuQVYzOZcZtvkV/MHYyexsICyKddeUYBt2byhObXCxpjPeVf8P3YNACzA9cV2C98w/nXRUlZK6tkX12lYfv+86350IRVTApNejCBT/32H423MWOmsNzRty3ykxd9nuZcq7G+3xQwDAGk1eSqRfTJP5RUd5/8w0+/W5b6nEML7oeOMcN2K3cgCVGw7doC/UnAJuY3rFCVFIBbO8Cnam5LY4uMBKPZo9Pxwj1ZLDeF7WlC5ZGcaacxuFLAI/K7R+RyZwtaaq9xZfN+M2SVMxZVlewsEMkxA25nSaoG1mIJvxY9f1j9B4GFbXp3YUo1m0N7bM9fsbgK8Ju/YR9s0/Bj6DAmC7dIdMm+xZ3MYuCVZfSPe0gE14+9iW56kgVU+5qf5NvlqwpZWLHu6DuvNzpst+Ho+UfYpbxXAJQRpf5T8IYqPCEPZ2117lc7ywRQs78DEbkoQy6Lv2CAjUTpC+5P4/YVJhscXH9KTCtHcVQYfv+FBLIuvUqk3fiZCMQL0d2Q7w2gbEF+w7rQuzU3xr9Jx9f0Y8N7MVCKvnwGmyg05gG2rJZegKCjzurCdGV6HGGiYFzcuoZm/1o04JkxWC3nR+fv66NwH/KFp2MJt5raVt0bXTj/bZXmBWO5AX/91Bgfm/jyFMjdRFm8JTmGj6FFo+Prbse+TvmD4aYCTBty5M2SRnZt6PwFBOpTDYje5XaYmwIWm14GPAQ4RMylYHzm4vgdBFvz+vyXm4CcHzhqm6SXaFQC+NZQVj9Id+ntZLCawzUXB0wKXam1aiNzOoTRULQ+13IieLabNI5s6qFSZTCA+w1ICSXXBpM/NWyHot7q/qB+8fedwbUpiyqX9bP4kAgdAiNLhdhj1GjGIvf0peqH2twVuvP5NJMw9zg6/3s8WzwbeSKrjd9c3EnCYNz40R3uVb+/6dP/Po4i77qLRFGfSgZOEdea8tAzP2Nz1MctMIBDkpik3AA4sHkAC4P/Ya0fJaycL4qU5zEpRCOEOJxGE+6gS7XTRv8W82feDy3lltfJ/XGxTP5J9/dAfNS4GnN3VFPJa6hy5FByY8Xt24WWu/w91OVzfBURzR1Tx/UzNIVhI6NiDSnczbtmvSZ4zm/Y72rxHSZQgualnHcp3Ey8ztisAT/PulQasgPxjcWHbKPW1DioLgAsIJKS18ZTUi1rWp7mCGqVF+SeYvhfSx9YH7nrpenrSLIpbwTv4Pt+GmZRA9mQlzwv8Sfi2X62gEcfeOWZGaOu77FQ6B3EQAaTWYFXk8QYgFcpu9XVupWC2weisSWWjmWIUIkBAUEiBKpqPPW0OUBWIDne7rKh4nKE1s3AFlmx+ei2+avQ3YJuckGqLGYi5TCarop5A6pSNU2ur/m5p9nUrTHYxYZpegzufEpo131bKHfDoEiGc8HXwVrta9y0B942rT/Id9OVpNlLCLqknE+x64T70vG/4kEyIkHqh6zp2XBKNhMRSwNb0whO0yQyRkoQK0WXPT4p4ciQn1E62HfI2qAHtlDZjo+jMRjGi6ryDcS+tYK5zCkfqk3o8rdpHln8u57OMHc6arOl2ywfPQs4gKezSHPPtobkcnH6Xd4btH5MFCcq48knoxPoQFXctNm2rCwpcV7vWNxIqk1PZxe/LDJKGoXAt+ZFlCLGmi0NIkbzFG0Epk5uBecUn7FnEYE3AR17nRpjHDjexjpjIo3bxUqFPg1vwwCRVWm8hAD90bmIV0kccfYK1Wd+CcLLhk27zohO1harSQxdPtIdUrkrqMfbESr3fYlFI5QfWp/JlUfP576KlhSfUP9W1juFgKSB6pz6MbGsDw12J1jJL88VUfSTb2ejP09/fdKZzFsBWtew4sIe7JQPzIs/u/PvwiZrPTkHiInQyhqceZVDkSBsN/pKKz7GuYeIwuwuukzVvcfHTLLjcBiQLmJ8oI9nwsnZmvepFMlWX+o/53Ks7A0PQ9D2iVMlgcY9sTrx/XEJl1oY7ijU9MUwRHLKwkF9KzLoPPt6iVzr+Xl61cdy8AAJcLzQPtoqacKUQW/tPaS0nmP/QdfOR5Bff2zscF5eiGUUln4GpSm/Y1QUDr3PHxd4m/w5Gm9FIetXu8t1OZyQhOEX7QB+gHrc0czeTIOp87BnnobHCrAe7pavVhG/rvyl9+jLkChMBzHGugsuk+5+hc22wqhqqK/QTcBo94nER9j2AcVpkkz0p1kGBI/noM+ZBZjxkjjK15FIF8ZLUsvkA6OHC/iFYT6LzbImalu/4xtPpMBW5PdS3Ih+NPH3vaP8Tk+vClnBqZ57BEbktUkeS046vBGfLqKJNwfgAhVLjD+/7bGHhcA5OFetaDoyLL+L6NveGoem1nd2qmOHAFQATXnmnK5nAwhz8AWjGuNMS1HFKyMRSpTtsoKGzaWjFTtfsz61G61iwPKL9MhMCIfQwlbE+Jj8jQ9AYK28isfyTlKd04+y8/vtAJxQnH8RZ5IMSJmVHKYtpI8UUypv1IbB5IPJTRa2MNcC/NssNyBDrJ/SHcTejKDY7rU0EbB5QYvWa3Lb2cx7gdGeVJE056bxt9pV1ee4rPGXlA4qqKkfZaLzWMcV4q3GLsnC5dg6QeLvA2QTglCs/oUf2ctq5c3AD8TAtSLY+RY3AbJyiq6kUA3kwhpB3Vp/isiLvhjKnbq3WDlYWDdyyDgg9uDWEhZtbx9T+gHjFa647bh+IJqY5Bj8YFE+m2AwnSvdnxdTuXxOtsPiyuHBQN6kTkOhfg4/6SN/S2r9xZu54ZvTmUmPVjyJwf6LlFVu906mdajkfmT0J+pGyD4GQAx0tXxcpbtbu5WLGIXQmYwpO9bvJ+P2MhvcQrecwvK5BYy/ge1rJAmMa/npVYi1Baq2IGyvyTuRsFVPrMY1ZG1eBpC/h8VQACoRsz4MI16rDnTTEX5tffYoB6no1BDa3QgX3rlBzEp/0BZuQ/GUGasBxwH5YjNdnV+qC8eBB3q2DQ32FBAu/z5uMddlCwm4/Mw4n2Gmd34iSb0KTuG8wbLOfL0VxGwvpq3YplLwSrzZR3bxFGyH4T5LAYpqMtS9OzbAqvj7X/83h4DuhE0MRNoOQzECsYNWZLMYfbHKglv8NzyslzWWJ5QhJ44zw2E0jDf+ZzXnjSwhcEXRBRFgBxMyeA+Dp0oB3nvP6sUvKVAgLUDEnQD97junafr3wcoXChhJslLfCc3ddPdi9/boBDvQpXnDbm//5W8s12CAxevu2IFVSkRqYI5BjLbez5ocIlrUjYGdpIypxO24yFMM1QkDYD1wJ/Gs+g5ehyZwhyWgoGV9ULBJUsT+Or/tq/p5uu4mDpMcY8ShrQPb7NssSUFCTIsHT5YuZY7WT6bZMMnRyNWMAKttemJbPp1Hz9tfdht+3t82BeZQRsDpR6+hhRApDq2Om7cwFi0riU5PXESpDAcaFQQkXTSsg9gHDfO+zTwfytu57wOPuymnE6zwriv7VS27rYO4ELvXu3Q3Sa2dP6FIpPOOs7aGAxj+9gStakjZvn9l+FFqDOUv1tqy3G9+aEgEa02Y8BlnCMtN91uf60hHpYyZCOg4c95HNwUh97ZEWo3oY3yOYUvTSlybXH8itoJM9WyGD369d0+KV0q/ZiT98Udcv6VzU7giTFrQbFPwv34e+Pd6nb3FW77+H+31gcb/2OtDFLLTdWkOPuBmRINsSnQfMVyPyYz9U8wiqecgXHzoV+lLjcwy0mYx7AuLSrT5+EuyrAoI19/iewbuIYv8zRvyyZdzhayHTppSCKUVxk5rPaAr2eYU4eGenlqIY0XJlpX78IaufjzUCH1A2TRS8vMMw2HknwHKJOXXyYm6bDvVInExio498+qs3HvDDBkiy0TN+qBUkljXtgoB2+6sy+oxapctw3H1TVtJvn8Flw1iXQP7JOF1JpylcDwLPNhxJ+X4L7YTZCuXXyvGXnHUuW5mZ6WACDilTg+Hfi3YyjVBJVtX4sp5MvASUguavIRf4/VF7mx76ivgLhK3pImCT0txRIrMna4xIhL+BeDrF8ZOx6a80RoZdjfjp+4dA54bEUVDUeD5g+Qj1RFLD/wlNw1EkVFwdqt4T4D0g1LFPnM5qzvkJmOAxk+HqQqCPybLpobRF3xhlu3Juu1DhPX8iV8h6iQHOMuTkhJB8NNoZ/l31s6Jydx2NLsPrxQV68Oaj/lMKSIRBhnWO9fE0/5HyR6q864YIXaB6wGlmdRYRky6eSzO+Uy1ouzxsFD1zoZ0L0VOnK/m8DmeLTvS/SQ45yIf0rWcupZHAmU/uKvS8FUMa2FQJIjf8BLuwwGiYSeLF8DCeMlivKl5Zb7gP1qjuXHtNDsxiCzex+/6ZqJc2iTK7OnhqjdFacPRXOVeIZV881QFzoYC62gEgAbzw8q4UmilkSH8AD3A6kmVQu+rRWp0OlQA7Q+KJG/j1WUMPII8c1xyxdYP357R9gDwPfo9EPLO8lU/2+YtBUP6uavONCLu52Fcdw9oxA8bk6/0rWzt6vlwi6jf5nlbZ3TkJobLHZ1kGuOiDCsIGbarxdUf8vA5O3pS4ZZLFUQo1SYn3frQRVd+IaLulbzo+QN7DNCYVDD0eJYWUIOin/65sMTlI2idhGOhRvlrJvWbNMM4Vt98CP/2g3s/a8BfvrbvFdWfFD7oTvx6dNWzPJub1OX6g0OGZUTb+OE4cIPA3pnnaIlYKzNOX4NciZUpRUTEy++IX8PK7aqe8CUxQK66roMqpBBoornEgMF3QYD6EUKSmF7uLfa4/6zeTAW46rMlHdqVBLFkbph7O6sNT6YsKt+B0LLpkeQxMoxJZiEZaAwmbAnQeZwQCFJI9cmoClgxb1BkF8kSq5Hy8y04a7RCI2WoJ0X1A/cOwUy+o2SWGEXhxZbvxrrb/bd0VjzrX9ZVrI2IglT8zEM04/3ZXvLxy9tobPGpzNA6amWPK1pMUQDC+BA++gwq6Xy1vYMi3K/ObXEJMMBYOCN/vnoD0EYD/ahbcI3ZVzCBJtHoXIxX+aiKFZqeA4gEj2VY352kTR5/ok0vJP9Uy7QfuCvqP5NN6xu8NSAg7pyaEodJfMBpLITPmi0muqv02E+XFERk0kEjuy8vDnEZwz/iUfS5A6RAUEIQbWac0eaNe0m/JjenyqGK2GiffrjBBPoBN8rgVwyI1X4tcmd+BGpci4ky1RVeKNvbegPBzc+NAPnwHS2ieydBH+i8E4P51w4MlMX3IfucDgsRWDyzIsgro0M2lMqcRwPEJiyc0lioLAQkrgAI8gr3U1aYob9BpFG99da+DlepHkn2Pph2YV6/8A1A6ACefZFQk0Sj4w/TkAMoyqgAd4mbNoysNoAspjk2ukOq6pKxpotfbjEJNwmhQ4qy+qQoh+ARB3Qt5Nf255ds7TReAw8vDcwSP1Dq5GSFUSiqQJWysfSsRCNIrScNo5XzWwMszyFDxXJFeAFMcSwECbPOlKzga1WAy/rNyxkFVtLiwgOnsQvuLTZ7ILZLhqPpO2F2wg9tetGjTyQej/B10+b3m/bPfLvDLxGbnjZBiEQR7aVC4RR+ts3hymcTPe0REq8ASAKVF1T17u8dDP4YbeW13L/v38fm5mP3XRWmrKLMtBpofUx6kbr4n93IMOnUerMvubOHg/chbY8vygPb6LvjF4364O2hzBk77QnbHSXInoCGdbpzn22MnPXeJ+e5HmIqrpC9fhABJVqEc8EFNcmOlWHHXDpJ/gVZlBLIxw55JcVNIZXDM08MARVO8q3y4tgyksEzZ6ufxU6OcsmETzBtuEN0QUToZpjPtXudrjKgrv6BCz9SHmhjW/enqy5GKzUOcaKM/F777NHVhKVAE1ikK3srPUj26wiqPLqI1iwrQ5rpuaeMSunNrJNfu1fJB3gQufaWhJEdhsxPcsImUM+N9DqprOKT6X2neL2vBTqCf++iaFv1MxINNfTRLC1MGeuwyBA7uCzJNmXlDiwIeSdcT3RUUIfmUjdtE0FFSsRQl80CFsGQEs7K8ndSyIlrPTzFfhUPE14cZfdpLOENpZ9Hn7hnJDUUWmjUc2V3RQdZIgL/jHfJIFSwSB71K0L3eDSqxjLq9dHBwWwADQK/mbfsQ1jYES26kvWhrSEA7A7AlVJNXBH0IXy/9r2Dn4/Fr8ggl17X8T48opw/HkEfUBB4TJlYsspBZGupukFt/JzHxIgH8Mljzya/iSnbR8eyBooUcEt1MdSKTIamo50I0iXstJrRYkvN2xIfQq2UsgEDziJyXObteIINvNIEVK404lY/8ViTQBjAmOYdLhEwtJ8pgI973G4Orh5Xe+6UjJ6IoHi0mWDPBNSAL76ilkPfPJ52HmGDvn4J9jX99dEaCektVpjcYDBNmHld75rt/gI3OO3IQ/yC2wxoc80kvzQrw1C89MaqWfI3Rd62mWFkUJfFITT5+g292CAlyB2Mb3CScnPiN3gk9PK1o7dnPbrp1O24Pi3qIJLqUemwXAQsS4aYCl1Upv4KTdAmDXAM5BfgASopllAhT98z/7lCNRJ3SulY6kzyi3oY+aTmkKZzO1SnzOOiRuxqoxN5GXcf6pCe9q4p8Uzct4z+lmO4B4gfQk9AbBFHwERiScvqEl93ydoDyMZLH5dTOw6N7pHtayXhJx3/lSVTLXnm7W48/CpWrmrKIEQ/LxOBMSZD9pFJqluL4GlfpWyhBxC+BWuxok1MH3ulUPgRIl6PqOLE1WRde+lB8gHBgFvx+otgIHaAA5P5usuz7fXaVqpYQOo7yTNPvrfRx6t5dwdhjVaTZAqxhoblOB6Of6MqN+ESlD5vjvEyQH75d3ymPYmhNaxl9H0zS0OGB6S6Zh+ghnKo0lb6nK2XSYrjcV9lOn94z5JVnMWCY769r4qskJWsatCCKmtqYei3WRIoIICEAf2aZ8aoSDOCKYR8Aab7tdr3y8jAfVad0tcU973qzNY6upGYq51uP6Su+RSS8HAzz2ParniMwNNrjB5gL6qypyRKwz6rAFFS0f1AgUu9ockw8spckn9AIyQrvp9avY1DGKTM1rdCYyLHjMr9mXmGHFSAcCjyy8yZo59hN9unJPeBfeVgY8CZp4VButXZhez2W0PydLlvO0eHkq4+FvM1FHLUBVr4lbWiQeQYmjHnkjQhg073/cpmfPC5W/FSNcXOx350dET6Skxh8jt9mUaOmCYQPpQWnZHVO36DXqQ28PLIYEGYGgw5BGeXXR+Fn4RxXmJUwdLRshBcHFze5mGiQl5x/FQIpx37qnHL/F7Utzn1OkS0Q7Laac/rp3wrjZzQ3IZg/bBsiij99uzJRgr6lgtbieNULMmRTIolfOBR+Hzrf3sYJmWXtRJbOFu7efOTH4WMGiTBzpWArtkQTxMwbXNZmnVRrKedYUPBl1qdH6kvboO6KVQHTHpQuHmQH7UQmsseys9Ax4I9jNVKUz6tbpBSQxdbD01zxJhGGaxTlQ/erxRd8xVYp09Z4bm0ljTceAjajDKktUdc14LW+6s8xlLeUJNOi8zZg0P3s4v5d+QJFajyIlORzUHKZ/1VtR3mqUgn0uyMKBgHgFtU0En0NcvcXI4NOhQIoQYCm2qRjSfYmUGJe2P0dR0ZB6tQ6QJPK0De/r0M3aNbhvjg3yk2PvT9WiuBgS/zxA9NCaI9pYHTF0Fy2yu7BBWj6S93XMpsGmBnKl4j3Rrx8JJMF0/Qfi9Dho9SLY9JDxtGBk0BmW9d+ybevMGyz/X2qYVkwF/szWIWXsY/egQSshH5ADj9GTI1ybk482YZGwL0I8q/HMlLj21DrLt1pg/SztW9jnNMxSGjES0BaadFcBG8pt9mDt7hj43O56a/ROlL4U+3hw6cOaqvDm8l+qn7uI7JPGBhmQgv2HzAVgq+jGSV/p2XBsSjaI9MZ5yy/LFgEx33mIrXvmMTJj+y0DRIVCDrl1zpR+BUwfp9BxMMbL4OXFgFiOEdZx5VpBvrmogMr6bf+zeW4VasNAHlhMsRK+fiFA/2Hh8LmQvla5w/W7j2Py4lRuDD3lz2fehJ7Lo0AMwf0DjkXGW3gBZ1kdIIWFX8x9QhSEcBvxWVyZXOw7aHnjtO9nFxU35t5vyQymRx3cnxPBakjjNFIC902Y+0vkcmIBJLfamrVSffxnlWViVWncTGFKAIeduTxzR+LDkz2Y8jq7rjdP8czjAKZxy7wxxEzkBaJgRYUjM1U29Z40f912Wmf/wT", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Country = _t, #"Image URL" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Country", type text}, {"Image URL", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

