table Sales
	lineageTag: f4ac2b27-8992-4fd0-9bde-c357bd78a335

	column SalesOrderLineKey
		dataType: int64
		formatString: 0
		lineageTag: 57484f8f-4bca-497b-aa51-74f24b7324d5
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: 1ca82391-1d68-4e48-b385-b5915971c102
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: c1b639ed-4992-4421-853f-2e68636eac1e
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: b21c26f8-844c-480c-a54b-89e9dd54d222
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 8547d722-2008-4ff7-b974-5ec60cd6529c
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 7590683f-c92f-4dfc-a5a0-c63b3d20c4fb
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 530bf15b-f64d-4b40-9f0e-c9c6dad9a23a
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 058c46b4-e73e-415f-988f-6f2a161b0d83
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		formatString: 0
		lineageTag: d335a489-18f6-42f4-8b05-169c6327bbad
		summarizeBy: sum
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		lineageTag: b39435eb-79a4-41a7-b4b8-dcc1be94be84
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extended Amount'
		dataType: double
		lineageTag: 477923ee-c75a-4711-bb0e-2e886f7c61b8
		summarizeBy: sum
		sourceColumn: Extended Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price Discount Pct'
		dataType: int64
		formatString: 0
		lineageTag: 97a8880d-4363-4244-a361-f794c9f2fca0
		summarizeBy: sum
		sourceColumn: Unit Price Discount Pct

		annotation SummarizationSetBy = Automatic

	column 'Product Standard Cost'
		dataType: double
		lineageTag: bd967a30-6496-47db-b223-c991d1be53de
		summarizeBy: sum
		sourceColumn: Product Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Product Cost'
		dataType: double
		lineageTag: d064e6c8-a03e-4f2d-b266-abef71c58a2d
		summarizeBy: sum
		sourceColumn: Total Product Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Amount'
		dataType: double
		lineageTag: bb4bc785-36f0-449e-a099-6d8369a1b6f6
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eda2ad69-9f94-4fbf-be8d-e47007ec945b
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 588e45f2-a42a-4aea-9e2d-c9de9bbff7df
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: b0f59d25-ac59-4620-a8eb-9d9e8fca478f
			defaultHierarchy: LocalDateTable_6c1fe297-b102-4eb2-852c-7a546bb72f50.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Inforiver Super Filter Webinar\AdventureWorks Sales .xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}, {"Order Date", type date}, {"Ship Date", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Order Date] < #date(2025, 3, 31))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

