/// Primary transaction fact table at Product × City × Channel × Month grain. Contains only foreign keys and numeric or flag measures — no descriptive text. All labels resolve through the three dimension tables. 63,180 rows covering 18 months.
table '[Fact] Sales'
	lineageTag: 1609937e-0745-4ef4-a93c-b83f2b369494

	/// Surrogate primary key for FactSales. Hidden.
	column 'Sales Key'
		dataType: string
		isHidden
		lineageTag: 93364f27-5e2f-433f-bc08-8c2e3feefcd2
		summarizeBy: none
		sourceColumn: SalesKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Product. Hidden — relationship join only.
	column 'Product Key'
		dataType: string
		isHidden
		lineageTag: d44b5472-9746-4975-ab26-a3809d4deab2
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Geography. Hidden — relationship join only.
	column 'Geography Key'
		dataType: string
		isHidden
		lineageTag: 21067990-fe19-43dc-b013-89e374910df0
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	/// Foreign key to [Dim] Date. Hidden — relationship join only.
	column 'Date Key'
		dataType: string
		isHidden
		lineageTag: 493f82bf-9108-4ca7-a369-8bcd26617e0c
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	/// Degenerate dimension — Modern Trade or General Trade. Drives channel-split analysis without requiring a separate dimension table.
	column 'Sales Channel'
		dataType: string
		lineageTag: ea4b727e-6c29-4b70-bbd1-882b8647377c
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = User

	/// Actual units sold in the period. Primary volume measure for TopN by quantity demos.
	column 'Units Actual'
		dataType: int64
		formatString: 0
		lineageTag: af06ab93-04ee-49ef-abdb-6262902a7107
		summarizeBy: sum
		sourceColumn: UnitsActual

		annotation SummarizationSetBy = Automatic

	/// Planned units for the period. Paired with UnitsActual to compute volume variance.
	column 'Units Plan'
		dataType: int64
		formatString: 0
		lineageTag: b62077ab-ea03-4e75-9023-c7975ebb8202
		summarizeBy: sum
		sourceColumn: UnitsPlan

		annotation SummarizationSetBy = Automatic

	/// Actual units minus Plan units. Positive = ahead of plan; negative = behind.
	column 'Units Variance'
		dataType: int64
		formatString: 0
		lineageTag: c0944692-c0e8-4c18-afee-f2229c25855b
		summarizeBy: sum
		sourceColumn: UnitsVariance

		annotation SummarizationSetBy = Automatic

	/// Units returned by customers in the period. Used to compute net units and return rate.
	column 'Units Returned'
		dataType: int64
		formatString: 0
		lineageTag: e600c6c2-49cb-451e-934e-6c2f32429be6
		summarizeBy: sum
		sourceColumn: UnitsReturned

		annotation SummarizationSetBy = Automatic

	/// Standard shelf price per unit in USD for this transaction row. Matches DimProduct.RetailSellPriceUSD at generation time.
	column 'Retail Sell Price USD'
		dataType: double
		lineageTag: 3fdf0548-d70e-4bee-9fa7-ec6df4826f4b
		summarizeBy: sum
		sourceColumn: RetailSellPriceUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Promotional discount rate applied to this row — 0 to 0.20. Zero for non-promotional rows.
	column 'Discount Pct'
		dataType: double
		lineageTag: 4fcbea10-fe1d-436a-9371-1c0fbc8ee66f
		summarizeBy: sum
		sourceColumn: DiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Effective price after discount: RetailSellPriceUSD × (1 - DiscountPct). The NSP is the revenue rate per unit.
	column 'Net Sell Price USD'
		dataType: double
		lineageTag: 940a39a3-b131-4335-8f64-fc6eb5bffb5b
		summarizeBy: sum
		sourceColumn: NetSellPriceUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total net revenue in USD: NetSellPriceUSD × UnitsActual. Primary revenue measure for TopN, Sort, and variance analysis.
	column 'Sales Amount USD'
		dataType: double
		lineageTag: 7fafef7b-3ab3-4660-bb7c-3b668d97ed71
		summarizeBy: sum
		sourceColumn: SalesAmountUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Budget revenue in USD: RetailSellPriceUSD × UnitsPlan. Compared against SalesAmountUSD to compute VarianceUSD and VariancePct.
	column 'Plan Amount USD'
		dataType: double
		lineageTag: 6baffe93-14c7-400b-800d-b96f4801bad5
		summarizeBy: sum
		sourceColumn: PlanAmountUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Cost of goods sold in USD: UnitCostUSD × UnitsActual. Subtracted from SalesAmountUSD to compute GrossProfitUSD.
	column 'COGS Amount USD'
		dataType: double
		lineageTag: 23fb0955-dfae-4cb1-88ab-e92c84e2ec10
		summarizeBy: sum
		sourceColumn: COGSAmountUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Revenue minus COGS in USD. Primary profitability measure — drives TopN by profit and gross margin analysis.
	column 'Gross Profit USD'
		dataType: double
		lineageTag: 5aba757a-a63b-4cfb-9346-db8e6baf332e
		summarizeBy: sum
		sourceColumn: GrossProfitUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// SalesAmountUSD minus PlanAmountUSD. Positive = beat plan; negative = missed. Used in Inforiver variance waterfall and conditional formatting demos.
	column 'Variance USD'
		dataType: double
		lineageTag: 0b41ef07-59e1-4b0c-9a66-cb6bd96b23e5
		summarizeBy: sum
		sourceColumn: VarianceUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// VarianceUSD as a percentage of PlanAmountUSD. Hero products average +14%; Laggard products average -16%. Creates strong visual contrast for Sort and TopN demos.
	column 'Variance Pct'
		dataType: double
		lineageTag: 07adfebd-76db-4de5-833c-6acf65871d3f
		summarizeBy: sum
		sourceColumn: VariancePct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// SalesAmountUSD converted to local currency using DimGeography.FXRateToUSD. Drives the Inforiver Localization demo — 12 currencies, 12 locales.
	column 'Sales Amount Local'
		dataType: double
		lineageTag: c416311c-82c4-4059-aeb0-2f936baff297
		summarizeBy: sum
		sourceColumn: SalesAmountLocal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// PlanAmountUSD converted to local currency. Paired with SalesAmountLocal for fully localised variance reporting.
	column 'Plan Amount Local'
		dataType: double
		lineageTag: b3f7191e-9c9d-4a77-b50d-e799c9f1f926
		summarizeBy: sum
		sourceColumn: PlanAmountLocal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Value of returned units in USD. Subtracted from SalesAmountUSD to compute NetSalesAfterReturns.
	column 'Returns Value USD'
		dataType: double
		lineageTag: ec7abca8-a852-4781-ace8-dddd84346a16
		summarizeBy: sum
		sourceColumn: ReturnsValueUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// SalesAmountUSD minus ReturnsValueUSD. The cleanest revenue metric after accounting for customer returns.
	column 'Net Sales After Returns'
		dataType: double
		lineageTag: 5ea06c48-a359-4481-b3c5-0f2b3c93c535
		summarizeBy: sum
		sourceColumn: NetSalesAfterReturns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Row-level gross margin percentage: GrossProfitUSD / SalesAmountUSD. Aggregated in DAX measures to compute portfolio-level margin.
	column 'Gross Margin Pct'
		dataType: double
		lineageTag: e102e806-6826-4f91-a07b-6c4490fec1d7
		summarizeBy: sum
		sourceColumn: GrossMarginPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Yes if DiscountPct > 0 for this row; No otherwise. Use as a filter to compare promotional vs non-promotional performance.
	column 'Is Promo'
		dataType: string
		lineageTag: b8b16570-ddae-4c87-b0b8-179197568264
		summarizeBy: none
		sourceColumn: IsPromo

		annotation SummarizationSetBy = User

	/// Estimated volume uplift versus non-promotional baseline, expressed as a percentage. Positive for hero products on promotion; near-zero for laggards.
	column 'Promo Lift Pct'
		dataType: double
		lineageTag: d7198d63-1c51-4e8a-89ce-31fe4191720f
		summarizeBy: sum
		sourceColumn: PromoLiftPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Proportion of stores in this channel and continent stocking this SKU — from 0.65 (General Trade Europe) to 0.92 (Modern Trade Europe). A key FMCG metric: higher coverage means the product is available in more outlets.
	column 'Distribution Coverage'
		dataType: double
		lineageTag: b2c3e345-ec4f-43c3-aef3-a9cde13d0f5b
		summarizeBy: sum
		sourceColumn: DistributionCoverage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Estimated days of stock on hand based on shelf life and sales velocity. Low values signal potential stockout risk; high values indicate overstock exposure.
	column 'Inventory Days Estimate'
		dataType: int64
		formatString: 0
		lineageTag: e0b9647d-b1b8-40cf-ad19-b2b7b1564199
		summarizeBy: sum
		sourceColumn: InventoryDaysEstimate

		annotation SummarizationSetBy = Automatic

	/// SalesAmountUSD grossed up by DimGeography.VATRate. Represents the consumer-facing price inclusive of local tax — relevant for pricing compliance reporting.
	column 'Sales Amount Incl VAT'
		dataType: double
		lineageTag: acbe70b4-0f80-41fb-aa5c-67d4c101cd9b
		summarizeBy: sum
		sourceColumn: SalesAmountInclVAT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '[Fact] Sales' = m
		mode: import
		source =
				let
				    Source = Csv.Document( File.Contents( DatasetFolder & "\\FactSales.csv" ),
				        [ Delimiter = ",", Columns = null, Encoding = 65001, QuoteStyle = QuoteStyle.None ] ),
				    #"Promoted Headers" = Table.PromoteHeaders( Source, [ PromoteAllScalars = true ] ),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"UnitsActual", Int64.Type}, {"UnitsPlan", Int64.Type}, {"UnitsVariance", Int64.Type}, {"UnitsReturned", Int64.Type}, {"RetailSellPriceUSD", type number}, {"DiscountPct", type number}, {"NetSellPriceUSD", type number}, {"SalesAmountUSD", type number}, {"PlanAmountUSD", type number}, {"COGSAmountUSD", type number}, {"GrossProfitUSD", type number}, {"VarianceUSD", type number}, {"VariancePct", type number}, {"SalesAmountLocal", type number}, {"PlanAmountLocal", type number}, {"ReturnsValueUSD", type number}, {"NetSalesAfterReturns", type number}, {"GrossMarginPct", type number}, {"PromoLiftPct", type number}, {"DistributionCoverage", type number}, {"InventoryDaysEstimate", Int64.Type}, {"SalesAmountInclVAT", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

